[memory_usage]
disabled = false
threshold = -1
symbol = " "
style = "bold dimmed green"

[hostname]
ssh_only = false
format =  "on [$hostname](bold red) "
trim_at = ".companyname.com"
disabled = false

